# Generated by Django 5.2 on 2025-04-21 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Lower number means higher priority/better tier",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Designates if this is the default tier for new users.",
                    ),
                ),
                (
                    "max_reminders",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Maximum number of active reminders allowed (-1 or None for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "max_viewers",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Maximum number of viewers allowed (-1 or None for unlimited)",
                        null=True,
                    ),
                ),
                ("can_use_sms_reminders", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receive_email_reminders", models.BooleanField(default=True)),
                (
                    "subscription_status",
                    models.CharField(
                        default="free",
                        help_text="Current status of the user's subscription.",
                        max_length=50,
                    ),
                ),
                (
                    "payment_customer_id",
                    models.CharField(
                        blank=True,
                        help_text="Customer ID from the payment gateway (e.g., Stripe Customer ID).",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "payment_subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="Subscription ID from the payment gateway.",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "subscription_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the current subscription period ends.",
                        null=True,
                    ),
                ),
                (
                    "account_tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user's current subscription tier.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.tier",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usersettings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Settings",
            },
        ),
    ]
