# Generated by Django 5.2 on 2025-04-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="avatar_color",
            field=models.CharField(
                default="(#000000, #FFFFFF)",
                help_text="Background and text color tuple for avatar in hex format",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="receive_sms_reminders",
            field=models.BooleanField(default=False),
        ),
    ]
