# Generated by Django 5.2 on 2025-04-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_usersettings_avatar_color_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersettings",
            old_name="bg_color",
            new_name="avatar_bg_color",
        ),
        migrations.RenameField(
            model_name="usersettings",
            old_name="text_color",
            new_name="avatar_text_color",
        ),
    ]
