# Generated by Django 5.2 on 2025-05-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_receiveupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's preferred timezone.", max_length=50),
        ),
    ]
