# Generated by Django 5.2 on 2025-04-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=255, verbose_name='Dosage')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255, verbose_name='Medication Name')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, verbose_name='Repeat')),
                ('at_time', models.TimeField(verbose_name='At')),
                ('until_date', models.DateField(blank=True, null=True, verbose_name='Until')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dosage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.dosage')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.medication')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.schedule')),
            ],
        ),
    ]
