# Generated by Django 5.2 on 2025-04-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='achievement_points',
            field=models.IntegerField(default=0),
        ),
    ]
